############## Flows description ################
flows:
    -
        id: [0]
        name: test 0
        source: [0]
        pipeline: 
            - { stage: 0, mstream: 0,      next_stage: [1,2]}
            - { stage: 1, inference: 0,    next_stage: [2]}
            - { stage: 2, tcp_sender: 0                    }

############## Module configurations  ################

#### Media source
source: 
    config:
    -
        id: [0]
        name: msource_file
        type: file #supported values: rtsp, grpc, file
        input: ["../downloads/video/video_resnet50.rgb"]
        optional:
            fps: 24
            width: 224
            height: 224

#### Media stream        
mstream: 
    config:
    -
        id: 0
        name: input_from_file
        stream_type: file
        optional:
            batch_size: 1

    optional:


#### Inference
inference:
    config:
    - 
        id: 0
        name: mobilenetssd
        hw_device_num: 0
        model_type: bchw_bgr  # for example - "resnet50", "ssd_resnet34", "yolov3", "bchw_bgr", "bchw_rgb", "bhw_grayscale"
        engine_type: openvino
        engine_device: MYRIAD #for hetero plugin, use HETERO:GPU,CPU
        num_of_inference_requests: 10
        batch_size: 8
        model_path: ../downloads/openvino/mobilenet-ssd_fp16/mobilenet-ssd.xml
        inference_rate: -1 #limit ILB output's FPS. 0 means automatic rate limit, -1 means no limit at all
        inference_input_precision: fp32 # input layer precision. "uint8" or "fp32".
        optional:
            openvino_n_threads: 1    #number of threads to use on open-vino inference when using the CPU device
            result_processing_plugin: libirp_plugin_detection_output.so
            detection_threshold: 0.58  #minimum threshold for accuracy/probability, must be a number between 0 and 1
            max_num_of_bounding_boxes: 4
            labels_file: ../downloads/openvino/mobilenet-ssd_fp16/labels.txt
           
    optional:
        output_rate_control: 0 # enable/disable IRP output's FPS from the client (e.g. external GUI).
        collect_stats_frames: 0 #if this number is 'x' (where 'x' > 0), openvino will collect statistics for 'x' frames, and will save a new IR (xml/bin) with the gathered statistics  
        
#### custom modules
custom: 
    -
        module_name: tcp_sender
        config:
        -
            id: 0
            name: tcp_sender
            port: 9093
            subnet: 192.168.1.0
