############## Flows description ################
flows:
    -
       id: [0]
       name: res50_flow
       source: [0]
       pipeline: 
           - { stage: 0, mstream: 0,      next_stage: [1,2]}
           - { stage: 1, inference: 0,    next_stage: [2]}
           - { stage: 2, tcp_sender: 0                    }

    -
       id: [1]
       name: yolov3_flow
       source: [1]
       pipeline: 
           - { stage: 0, mstream: 1,      next_stage: [1]}
           - { stage: 1, mdecode: 0,      next_stage: [2,3]}
           - { stage: 2, inference: 1,    next_stage: [3]}
           - { stage: 3, tcp_sender: 0                   }

############## Module configurations  ################

#### Media source
source: 
    config:
    -
        id: [0]
        name: ilb test
        type: file #supported values: rtsp, grpc, file
        input: ["../downloads/video/video_resnet50.rgb"]
        optional:
            load_to_ram: true
            fps: 25
            width: 224
            height: 224

    -
        id: [1]
        name: msource_file
        type: file #supported values: rtsp, grpc, file
        input: ["../downloads/video/demo.h264"]
        optional:
            load_to_ram: true
            mbps: 3

#### Media stream        
mstream: 
    config:
    -
        id: 0
        name: input_from_file
        stream_type: file
        optional:
            batch_size: 1
    -
        id: 1
        name: input_from_file
        stream_type: file
        optional:
            batch_size: 1
    optional:

        
#### Media decoder
mdecode:
    config:
    - 
        id: 0
        name: conf_1
        video_type: h264 #h264 h265
        output_format: nv12 # nv12, i420, rgb4
        inline_scale: [416, 416]
        threads_num: 2 # minimum is 2 
        complete_frame: 0 # 0 disable, 1 enable
        hw_device_num: -1
        optional:
            gen_postproc: 0 # 0 disable, 1 auto, 2 force
            async_depth: 4  # 1 - 20 (default is 4)
            batch_size: 2

    optional:
        error_report: True # 0 disable, 1 enable


#### Inference
inference:
    config:
    - 
        id: 0
        name: res50
        hw_device_num: 0
        model_type: resnet50  # for example - "resnet50", "ssd_resnet34", "yolov3", "bchw_bgr", "bchw_rgb", "bhw_grayscale"
        engine_type: openvino
        engine_device: CPU #for hetero plugin, use HETERO:GPU,CPU
        num_of_inference_requests: 10
        batch_size: 5
        model_path: ../downloads/openvino/resnet50_int8/ResNet50-int8.xml
        inference_rate: -1 #limit ILB output's FPS. 0 means automatic rate limit, -1 means no limit at all
        inference_input_precision: uint8 # input layer precision. "uint8" or "fp32".
        optional:
            openvino_n_threads: 1    #number of threads to use on open-vino inference when using the CPU device
            result_processing_plugin: libirp_plugin_resnet50.so
            detection_threshold: 0.6  #minimum threshold for accuracy/probability, must be a number between 0 and 1
            labels_file: ../downloads/openvino/resnet50_int8/ResNet50-int8.labels
            hetero_dump_graph_dot: false # Generata *.dot files which show the affinity of layers to devices
            stats_image_num: 0 #if this number is 'x' (where 'x' > 0), openvino will collect statistics for 'x' frames, and will save a new IR (xml/bin) with the gathered statistics  

    - 
        id: 1
        name: yolo3_hetero
        hw_device_num: 0
        model_type: yolov3  # for example - "resnet50", "ssd_resnet34", "yolov3", "bchw_bgr", "bchw_rgb", "bhw_grayscale"
        engine_type: openvino
        engine_device: HETERO:GPU,CPU
        num_of_inference_requests: 10
        batch_size: 2
        model_path: ../downloads/openvino/yolov3/frozen_darknet_yolov3_model_stats_regionyolo.xml
        inference_rate: -1 #limit ILB output's FPS. 0 means automatic rate limit, -1 means no limit at all
        inference_input_precision: uint8 # input layer precision. "uint8" or "fp32".
        optional:
            openvino_n_threads: 1    #number of threads to use on open-vino inference when using the CPU device
            result_processing_plugin: libirp_plugin_yolov3.so
            detection_threshold: 0.6  #minimum threshold for accuracy/probability, must be a number between 0 and 1
            labels_file: ../downloads/openvino/yolov3/coco.names
            ssd_boxes_file: ../downloads/openvino/yolov3/dboxes.txt
            max_num_of_bounding_boxes: 8
            hetero_dump_graph_dot: false # Generata *.dot files which show the affinity of layers to devices

    optional:
        collect_stats_frames: 0 #if this number is 'x' (where 'x' > 0), openvino will collect statistics for 'x' frames, and will save a new IR (xml/bin) with the gathered statistics  
        log_level: fatal, error ,warning, #info,trace,debug

#### custom modules
custom: 
    -
        module_name: tcp_sender
        config:
        -
            id: 0
            name: tcp_sender
            port: 9093
            subnet: 192.168.1.0
